<a href="https://colab.research.google.com/github/OGTB/Py-playground/blob/master/netflix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import datetime

In [ ]:
df.shape

(8807, 12)

In [ ]:
df = pd.read_csv('/content/netflix_titles.csv')
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
for col in df.columns:
  print(col)

show_id
type
title
director
cast
country
date_added
release_year
rating
duration
listed_in
description

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

from matplotlib import pyplot as plt
_df_0['release_year'].plot(kind='hist', bins=20, title='release_year')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['release_year'].plot(kind='line', figsize=(8, 4), title='release_year')
plt.gca().spines[['top', 'right']].set_visible(False)

Count the number of Movies vs TV Shows

In [ ]:
df['type'].value_counts()

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

Find the most common rating for movies and TV shows

In [ ]:
df['rating'].value_counts().sort_values(ascending=False).head(1)

rating
TV-MA    3207
Name: count, dtype: int64

List all movies released in a specific year

In [ ]:
movies = df[df['type'] == 'Movie']

In [ ]:
movies['release_year'].value_counts()

release_year
2017    767
2018    767
2016    658
2019    633
2020    517
       ...
1959      1
1963      1
1966      1
1946      1
1947      1
Name: count, Length: 73, dtype: int64

Find the top 5 countries with the most content on Netflix

In [ ]:
df['country'].value_counts().head()

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Name: count, dtype: int64

Identify the longest movie

In [ ]:
movie = df[df['type'] == 'Movie']
movie["duration"].str.split(" ", expand = True)[0].dropna().astype(int).sort_values(ascending=False).head(1)

4253    312
Name: 0, dtype: int64

In [ ]:
df['title'][df['duration'] == "312 min"]

4253    Black Mirror: Bandersnatch
Name: title, dtype: object

Find content added in the last 5 years

In [ ]:
df[df["release_year"] >= datetime.datetime.now().year -5]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
7594,s7595,Movie,Norm of the North: Family Vacation,Anthony Bell,"Andrew Toth, Lisa Durupt, Jonathan Holmes, Pau...",United States,"May 25, 2020",2020,TV-Y7,89 min,Children & Family Movies,"Stressed by his duties as king and father, Nor..."
8099,s8100,Movie,Straight Up,James Sweeney,"James Sweeney, Katie Findlay, Randall Park, Hi...",United States,"June 26, 2020",2020,TV-MA,96 min,"Comedies, Independent Movies, LGBTQ Movies",When a gay brainiac with OCD questions his ide...
8125,s8126,TV Show,Super Wings,NaN,"Luca Padovan, Evan Smolin, Junah Jang, Colin C...","United States, South Korea, China","December 1, 2020",2020,TV-Y,3 Seasons,"Kids' TV, Korean TV Shows",A cheerful jet and his transforming pals striv...
8132,s8133,TV Show,Surviving R. Kelly Part II: The Reckoning,NaN,R. Kelly,United States,"April 13, 2020",2020,TV-MA,1 Season,"Crime TV Shows, Docuseries",As more women come forward with harrowing accu...
8437,s8438,TV Show,The Netflix Afterparty,NaN,"David Spade, London Hughes, Fortune Feimster",United States,"January 2, 2021",2021,TV-MA,1 Season,"Stand-Up Comedy & Talk Shows, TV Comedies","Hosts David Spade, Fortune Feimster and London..."

Find all the movies/TV shows by director 'Rajiv Chilaka'!

In [ ]:
df['title'][df['director'] == "Rajiv Chilaka"]

406                          Chhota Bheem - Neeli Pahaadi
407                                 Chhota Bheem & Ganesh
408                    Chhota Bheem & Krishna: Mayanagari
409     Chhota Bheem & Krishna: Pataliputra- City of t...
410                    Chhota Bheem And The Broken Amulet
411                Chhota Bheem And The Crown of Valhalla
412                  Chhota Bheem and the Incan Adventure
413                   Chhota Bheem and The ShiNobi Secret
414                              Chhota Bheem Aur Hanuman
415                              Chhota Bheem aur Krishna
416                   Chhota Bheem aur Krishna vs Zimbara
419                         Chhota Bheem: Bheem vs Aliens
420                  Chhota Bheem: Dholakpur to Kathmandu
422                        Chhota Bheem: Journey to Petra
423                       Chhota Bheem: Master of Shaolin
424                     Chhota Bheem: The Rise of Kirmada
2717                Chhota Bheem and the Curse of Damyaan
6297                                            Bheemayan
6645                                Dragonkala Ka Rahasya
Name: title, dtype: object

List all TV shows with more than 5 seasons

In [ ]:
seasoncounts = df['duration'][df['type'] == 'TV Show'].dropna().str.split(" ", expand = True)[0].astype(int)

In [ ]:
print(f"Tv shows with more than 5 seasons:  {seasoncounts[seasoncounts >= 5].count()}")

Tv shows with more than 5 seasons:  164

Count the number of content items in each genre

In [ ]:
print(df["listed_in"].value_counts())

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
                                                   ...
Action & Adventure, Cult Movies                       1
Action & Adventure, Comedies, Music & Musicals        1
Classic Movies, Horror Movies, Thrillers              1
Children & Family Movies, Classic Movies, Dramas      1
Cult Movies, Dramas, Thrillers                        1
Name: count, Length: 514, dtype: int64

Find each year and the average numbers of content release in India on netflix

In [ ]:
India = df[df['country'] == 'India']

In [ ]:
pd.pivot_table(India, index = 'release_year', aggfunc='count',fill_value = 0)

,cast,country,date_added,description,director,duration,listed_in,rating,show_id,title,type
release_year,,,,,,,,,,,
1959,1,1,1,1,1,1,1,1,1,1,1
1962,1,1,1,1,1,1,1,1,1,1,1
1964,1,1,1,1,1,1,1,1,1,1,1
1966,1,1,1,1,1,1,1,1,1,1,1
1969,1,1,1,1,1,1,1,1,1,1,1
1971,2,2,2,2,2,2,2,2,2,2,2
1972,2,2,2,2,2,2,2,2,2,2,2
1973,2,2,2,2,2,2,2,2,2,2,2
1974,2,2,2,2,2,2,2,2,2,2,2
1975,2,2,2,2,2,2,2,2,2,2,2
1976,2,2,2,2,1,2,2,2,2,2,2
1977,2,2,2,2,2,2,2,2,2,2,2
1978,1,1,1,1,1,1,1,1,1,1,1
1979,2,2,2,2,2,2,2,2,2,2,2
1980,2,2,2,2,2,2,2,2,2,2,2
1981,1,1,1,1,1,1,1,1,1,1,1
1982,6,6,6,6,6,6,6,6,6,6,6
1983,4,4,4,4,4,4,4,4,4,4,4
1984,1,1,1,1,1,1,1,1,1,1,1
1985,2,2,2,2,2,2,2,2,2,2,2
1986,2,2,2,2,2,2,2,2,2,2,2
1987,1,1,1,1,1,1,1,1,1,1,1
1988,2,2,2,2,2,2,2,2,2,2,2
1989,2,2,2,2,2,2,2,2,2,2,2
1990,4,4,4,4,4,4,4,4,4,4,4
1992,1,1,1,1,1,1,1,1,1,1,1
1993,3,3,3,3,3,3,3,3,3,3,3
1994,5,5,5,5,5,5,5,5,5,5,5
1995,5,5,5,5,5,5,5,5,5,5,5
1996,3,3,3,3,3,3,3,3,3,3,3
1997,3,3,3,3,3,3,3,3,3,3,3
1998,6,6,6,6,6,6,6,6,6,6,6
1999,6,6,6,6,6,6,6,6,6,6,6
2000,7,7,7,7,7,7,7,7,7,7,7
2001,7,7,7,7,7,7,7,7,7,7,7
2002,10,10,10,10,10,10,10,10,10,10,10
2003,12,12,12,12,12,12,12,12,12,12,12
2004,15,15,15,15,15,15,15,15,15,15,15
2005,19,20,20,20,20,20,20,20,20,20,20
2006,20,20,20,20,20,20,20,20,20,20,20
2007,16,16,16,16,16,16,16,16,16,16,16
2008,25,25,25,25,25,25,25,25,25,25,25
2009,28,28,28,28,27,28,28,28,28,28,28
2010,34,35,35,35,31,35,35,35,35,35,35
2011,30,30,30,30,29,30,30,30,30,30,30
2012,38,38,38,38,36,38,38,38,38,38,38
2013,52,54,54,54,51,54,54,54,54,54,54
2014,49,51,51,51,45,51,51,51,51,51,51
2015,58,62,62,62,53,62,62,62,62,62,62
2016,70,73,73,73,71,73,73,73,73,73,73
2017,99,101,101,101,97,101,101,101,101,101,101
2018,90,94,94,94,81,94,94,94,94,94,94
2019,82,87,87,87,73,87,87,87,87,87,87
2020,69,75,75,75,61,75,75,75,75,75,75
2021,29,31,31,31,23,31,31,31,31,31,31